# Generated by Django 4.1.1 on 2022-11-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='data',
            new_name='date',
        ),
    ]
